/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bell.glb -o src/components/Bell.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bell(props) {
  const { nodes, materials } = useGLTF('/models/Bell.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bell.geometry} material={materials.Bell} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Bell.glb')
