/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Irina2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/Irina_face11.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection">
          <group name="Collection">
            <group name="Irina">
              <group name="Armature">
                <group name="Body">
                  <skinnedMesh
                    name="Body_1"
                    geometry={nodes.Body_1.geometry}
                    material={materials.Skin}
                    skeleton={nodes.Body_1.skeleton}
                  />
                  <lineSegments
                    name="Body_2"
                    geometry={nodes.Body_2.geometry}
                    material={materials.Skin}
                  />
                  <mesh
                    name="EyeL"
                    castShadow
                    receiveShadow
                    geometry={nodes.EyeL.geometry}
                    material={nodes.EyeL.material}
                  />
                  <mesh
                    name="EyeR"
                    castShadow
                    receiveShadow
                    geometry={nodes.EyeR.geometry}
                    material={nodes.EyeR.material}
                  />
                </group>
                <skinnedMesh
                  name="Hair"
                  geometry={nodes.Hair.geometry}
                  material={materials.Hair}
                  skeleton={nodes.Hair.skeleton}
                />
                <primitive object={nodes.Spine_Lower} />
                <primitive object={nodes.ThighL} />
                <primitive object={nodes.ThighR} />
                <primitive object={nodes.Hips_Centre} />
              </group>
              <group
                name="Skirt"
                position={[0, 0.639, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.319}>
                <mesh
                  name="Skirt_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Skirt_1.geometry}
                  material={materials.Cloth}
                />
                <lineSegments
                  name="Skirt_2"
                  geometry={nodes.Skirt_2.geometry}
                  material={materials.Cloth}
                />
              </group>
              <group
                name="Shirt"
                position={[0, 1.052, 0.128]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.175}>
                <mesh
                  name="Shirt_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shirt_1.geometry}
                  material={materials.Cloth}
                />
                <lineSegments
                  name="Shirt_2"
                  geometry={nodes.Shirt_2.geometry}
                  material={materials.Cloth}
                />
              </group>
            </group>
          </group>
          <group name="Backup">
            <group name="Face" />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Irina_face11.glb')