name: Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'my-portfolio/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: my-portfolio
        run: npm install

      # Will add for running tests
      # - name: Run tests
      #   run: npm test

      - name: Build project
        working-directory: my-portfolio
        run: npm run build

      - name: Deploy to Vercel
        # if: success()
        working-directory: my-portfolio
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod
